version: '3.8'

services:
  mysql:
    image: mysql:8.0.28
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: student
      MYSQL_USER: mck0506
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "9000:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 123456

  redis:
    image: redis:7
    container_name: redis
    ports:
       - "6379:6379"
    volumes:
        - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  backend:
    build:
      context: ./SOA-2025-MIDTERM
    ports:
      - "8000:8000"
    volumes:
      - ./SOA-2025-MIDTERM:/app
    command: ["/wait-for-it.sh", "mysql:3306", "--", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ./SOA-2025-MIDTERM/if.env

  frontend:
    build:
      context: ./SOA-Frontend-Midterm/Myfrontend/myapp
    ports:
      - "3000:3000"
    volumes:
      - ./SOA-Frontend-Midterm/Myfrontend/myapp:/app
      - /app/node_modules
    command: npm start
    depends_on:
      - backend
    env_file:
      - ./SOA-Frontend-Midterm/Myfrontend/myapp/.env

volumes:
  mysql_data:
  redis_data:

