version: '3.8'

services:
  mysql:
    image: mysql:8.0.28
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: student
      MYSQL_USER: mck0506
      MYSQL_PASSWORD: 123456
      MYSQL_HOST: mysql
    volumes:
      - C:/Docker/volume/mysql_28:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9000:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456

  redis:
    image: redis:7
    container_name: redis
    ports:
       - "6379:6379"
    volumes:
        - C:/Docker/volume/redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]

  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    env_file:
      - if.env

  # frontend:
  #   build:
  #     context: ../SOA-Frontend-Midterm/Myfrontend/myapp
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   environment:
  #     VITE_API_URL: http://localhost:8000

  frontend:
    build:
      context: ../SOA-Frontend-Midterm/Myfrontend/myapp
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ../SOA-Frontend-Midterm/Myfrontend/myapp/.env

